/**
 * EdgeProp lead scraper — click-based pagination
 *
 * Crawls three sources:
 *   1. Deal Watch section  (/property-news/deal-watch)  — all pages, 100% transactional
 *   2. News listing         (/property-news/news)        — all pages, keyword-filtered
 *
 * For each transactional article, sends body text to Claude (Haiku) to
 * extract structured leads, then writes data/leads.json + data/leads.ts.
 *
 * Usage:
 *   npx tsx scripts/scrape.ts [--source deal-watch|news|all] [--max-pages N]
 *
 * Requires: ANTHROPIC_API_KEY env variable
 */

import { chromium, Browser, Page } from "playwright"
import Anthropic from "@anthropic-ai/sdk"
import * as fs from "fs"
import * as path from "path"

// ── Config ────────────────────────────────────────────────────────────────────

const BASE_URL = "https://www.edgeprop.sg"

const TRANSACTION_KEYWORDS = [
  "sold","sale","for sale","acqui","buys","bought","purchased","purchase",
  "leased","lease","bid","tender","gls","enbloc","en bloc","redevelopment",
  "divests","divest","deal","million","psf","shophouse","industrial",
  "hotel","investment","jv","joint venture","launches","tops bid",
  "expression of interest","eoi","collective sale","record","caveat",
  "capital markets","warehouse","logistic","commercial","strata",
]

const SKIP_KEYWORDS = [
  "bto launch","bto exercise","hdb bto","rental guide","mortgage guide",
  "how to buy","tips for","what is","explainer","rankings","awards gala",
]

// ── Types ─────────────────────────────────────────────────────────────────────

export type Lead = {
  id: number
  date: string
  articleTitle: string
  company: string
  person: string
  role: string
  intent: string
  property: string
  sector: string
  valueNum: number
  value: string
  phone: string
  email: string
  website: string
  address: string
  sourceUrl: string
  notes: string
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function isTransactional(title: string): boolean {
  const t = title.toLowerCase()
  if (SKIP_KEYWORDS.some(k => t.includes(k))) return false
  return TRANSACTION_KEYWORDS.some(k => t.includes(k))
}

function sleep(ms: number) {
  return new Promise(r => setTimeout(r, ms))
}

function saveProgress(leads: Lead[], dataDir: string) {
  if (!fs.existsSync(dataDir)) fs.mkdirSync(dataDir, { recursive: true })
  fs.writeFileSync(path.join(dataDir, "leads.json"), JSON.stringify(leads, null, 2), "utf-8")
  const ts = `// Auto-generated by scripts/scrape.ts — do not edit manually
// Last updated: ${new Date().toISOString()} | Total leads: ${leads.length}

export type Lead = {
  id: number; date: string; articleTitle: string; company: string
  person: string; role: string; intent: string; property: string
  sector: string; valueNum: number; value: string; phone: string
  email: string; website: string; address: string; sourceUrl: string; notes: string
}

export const leads: Lead[] = ${JSON.stringify(leads, null, 2)}
`
  fs.writeFileSync(path.join(dataDir, "leads.ts"), ts, "utf-8")
  process.stdout.write(`  💾 ${leads.length} leads saved\n`)
}

// ── Article link collection (click-paginate) ──────────────────────────────────

async function collectArticleLinks(
  page: Page,
  startUrl: string,
  maxPages: number,
  filterFn: (title: string) => boolean
): Promise<{ title: string; url: string }[]> {
  const collected: { title: string; url: string }[] = []
  const seen = new Set<string>()

  await page.goto(startUrl, { waitUntil: "domcontentloaded", timeout: 30000 })
  await sleep(1500)

  let pageNum = 1
  while (pageNum <= maxPages) {
    // Extract links from current view
    const links = await page.evaluate(() => {
      return Array.from(document.querySelectorAll("a[href*='/property-news/']"))
        .filter(a => {
          const href = (a as HTMLAnchorElement).href
          const text = a.textContent?.trim() || ""
          if (text.length < 20) return false
          const blocked = ["/property-news/news","/property-news/in-depth","/property-news/deal-watch",
            "/property-news/showcase","/property-news/international","/property-news-author",
            "/property-news-search","/living/"]
          return !blocked.some(b => href.includes(b))
        })
        .map(a => ({ title: a.textContent?.trim() || "", url: (a as HTMLAnchorElement).href }))
    })

    let newOnPage = 0
    for (const { title, url } of links) {
      if (!seen.has(url) && filterFn(title)) {
        seen.add(url)
        collected.push({ title, url })
        newOnPage++
      }
    }

    console.log(`  Page ${pageNum}: ${links.length} articles, ${newOnPage} transactional (total collected: ${collected.length})`)

    if (pageNum >= maxPages) break

    // Try to click "Next" button
    const nextClicked = await page.evaluate(() => {
      const btns = Array.from(document.querySelectorAll("button, a, li"))
      const next = btns.find(el => {
        const t = el.textContent?.trim().toLowerCase() || ""
        return t === "next" || t === "›" || t === ">" || t === "next page"
      })
      if (next) {
        const clickable = (next.tagName === "LI" ? next.querySelector("a, button") : next) as HTMLElement
        if (clickable && !clickable.hasAttribute("disabled")) {
          clickable.click()
          return true
        }
      }
      return false
    })

    if (!nextClicked) {
      // Try clicking the next page number
      const currentPageNum = pageNum
      const nextNumClicked = await page.evaluate((cur) => {
        const allLinks = Array.from(document.querySelectorAll("a, button"))
        const nextNum = allLinks.find(el => el.textContent?.trim() === String(cur + 1))
        if (nextNum) {
          (nextNum as HTMLElement).click()
          return true
        }
        return false
      }, currentPageNum)

      if (!nextNumClicked) {
        console.log(`  No more pages after page ${pageNum}`)
        break
      }
    }

    await sleep(1500)
    pageNum++
  }

  return collected
}

// ── Article text extraction ───────────────────────────────────────────────────

async function getArticleContent(page: Page, url: string): Promise<{ text: string; date: string }> {
  try {
    await page.goto(url, { waitUntil: "domcontentloaded", timeout: 30000 })
    await sleep(2000)

    const text = await page.evaluate(() => document.body.innerText.slice(0, 8000))
    const date = await page.evaluate(() => {
      const t = document.querySelector("time")
      if (t) return t.getAttribute("datetime") || t.textContent?.trim() || ""
      const d = document.querySelector("[class*='date'],[class*='time'],[class*='posted']")
      return d?.textContent?.trim() || ""
    })

    let parsedDate = new Date().toISOString().split("T")[0]
    if (date) {
      const d = new Date(date)
      if (!isNaN(d.getTime())) parsedDate = d.toISOString().split("T")[0]
      else {
        // Try "June 20, 2026" format
        const m = date.match(/(\w+ \d+,?\s*\d{4})/)
        if (m) {
          const d2 = new Date(m[1])
          if (!isNaN(d2.getTime())) parsedDate = d2.toISOString().split("T")[0]
        }
      }
    }

    return { text, date: parsedDate }
  } catch {
    return { text: "", date: new Date().toISOString().split("T")[0] }
  }
}

// ── Claude lead extraction ────────────────────────────────────────────────────

const SYSTEM_PROMPT = `You are a property intelligence analyst extracting investment leads from Singapore property news.

A lead is any company, entity, or person that:
- Bought, sold, leased, bid on, or is marketing a property
- Is a developer, investor, or JV partner in a transaction
- Has a clear buying/selling/leasing/developing intent

Return a JSON array of leads. Each lead:
{
  "company": string,
  "person": string,           // key decision maker(s), or ""
  "role": string,             // "Buyer" | "Seller" | "Marketing Agent" | "JV Partner" | "Developer" | "Bidder"
  "intent": "BUY"|"SELL"|"BROKER"|"JV"|"BID"|"ADVISORY"|"REDEVELOP"|"LEASE"|"LAUNCH",
  "property": string,         // address or name of property
  "sector": "Industrial"|"Hotel"|"Office"|"Shophouse"|"Residential"|"Commercial"|"International"|"Retail"|"Mixed",
  "valueNum": number,         // SGD millions (0 if unknown)
  "value": string,            // e.g. "$71M ($943 psf)" or "EOI – guide $35M"
  "phone": string,            // if mentioned
  "email": string,            // if mentioned
  "website": string,          // if mentioned
  "address": string,          // registered or property address
  "notes": string             // size sqft, psf, tenure, lease years, special conditions
}

Rules:
- Create a separate entry for each distinct party (buyer, seller, agent are 3 entries)
- For GLS tenders, include all bidders + the winning JV partners as separate entries
- For EOI listings, include the seller + the marketing agent
- Return [] for pure editorial/market commentary with no specific transactions
- Only include residential deals if >$5M or institutional buyer
Return ONLY the JSON array, no markdown.`

async function extractLeads(
  client: Anthropic,
  text: string,
  title: string,
  url: string,
  date: string
): Promise<Omit<Lead, "id" | "articleTitle" | "sourceUrl">[]> {
  if (!text || text.length < 200) return []
  try {
    const msg = await client.messages.create({
      model: "claude-haiku-4-5-20251001",
      max_tokens: 2048,
      system: SYSTEM_PROMPT,
      messages: [{ role: "user", content: `Title: ${title}\nURL: ${url}\nDate: ${date}\n\n${text}` }],
    })
    const raw = (msg.content[0] as { type: string; text: string }).text.trim()
    const start = raw.indexOf("[")
    const end = raw.lastIndexOf("]")
    if (start === -1 || end === -1) return []
    return JSON.parse(raw.slice(start, end + 1))
  } catch (e) {
    console.error(`  ✗ parse error: ${e}`)
    return []
  }
}

// ── Main ──────────────────────────────────────────────────────────────────────

async function main() {
  const args = process.argv.slice(2)
  const sourceArg = args[args.indexOf("--source") + 1] || "all"
  const maxPagesIdx = args.indexOf("--max-pages")
  const maxNewsPages = maxPagesIdx !== -1 ? parseInt(args[maxPagesIdx + 1]) : 50

  if (!process.env.ANTHROPIC_API_KEY) {
    console.error("Error: ANTHROPIC_API_KEY not set")
    process.exit(1)
  }

  const client = new Anthropic()
  const dataDir = path.join(__dirname, "../data")

  // Load existing leads
  const existingFile = path.join(dataDir, "leads.json")
  const existingUrls = new Set<string>()
  const allLeads: Lead[] = []
  if (fs.existsSync(existingFile)) {
    const existing: Lead[] = JSON.parse(fs.readFileSync(existingFile, "utf-8"))
    existing.forEach(l => existingUrls.add(l.sourceUrl))
    allLeads.push(...existing)
    console.log(`Loaded ${existing.length} existing leads`)
  }
  let nextId = allLeads.length > 0 ? Math.max(...allLeads.map(l => l.id)) + 1 : 1

  const WORKERS = 5
  const browserArgs = ["--no-sandbox", "--disable-blink-features=AutomationControlled",
    "--user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"]

  const browser: Browser = await chromium.launch({ headless: true, args: browserArgs })
  const listPage: Page = await browser.newPage()

  try {
    // ── Collect article URLs ─────────────────────────────────────────────────

    const articleQueue: { title: string; url: string }[] = []

    if (sourceArg === "deal-watch" || sourceArg === "all") {
      console.log("\n── Collecting Deal Watch articles ──────────────────────")
      const dw = await collectArticleLinks(listPage, `${BASE_URL}/property-news/deal-watch`, 26, () => true)
      articleQueue.push(...dw)
      console.log(`Deal Watch: ${dw.length} articles queued`)
    }

    if (sourceArg === "news" || sourceArg === "all") {
      console.log(`\n── Collecting News articles (${maxNewsPages} pages) ──────────────────────`)
      const news = await collectArticleLinks(listPage, `${BASE_URL}/property-news/news`, maxNewsPages, isTransactional)
      articleQueue.push(...news)
      console.log(`News: ${news.length} articles queued`)
    }

    await listPage.close()

    // Dedup
    const deduped = [...new Map(articleQueue.map(a => [a.url, a])).values()]
      .filter(a => !existingUrls.has(a.url))
    console.log(`\n${deduped.length} new articles to scrape with ${WORKERS} parallel workers`)

    // ── Parallel article scraping ────────────────────────────────────────────

    let cursor = 0
    let processed = 0
    const mutex = { saving: false }

    async function worker(workerId: number) {
      const page = await browser.newPage()
      while (true) {
        const idx = cursor++
        if (idx >= deduped.length) break
        const { title, url } = deduped[idx]

        process.stdout.write(`[W${workerId}][${idx + 1}/${deduped.length}] ${title.slice(0, 55)}\n`)

        const { text, date } = await getArticleContent(page, url)
        if (!text || text.length < 200) {
          process.stdout.write(`  W${workerId} ✗ empty\n`)
          continue
        }

        const extracted = await extractLeads(client, text, title, url, date)
        processed++

        if (extracted.length > 0) {
          for (const lead of extracted) {
            allLeads.push({ id: nextId++, date: lead.date || date, articleTitle: title, sourceUrl: url,
              company: lead.company, person: lead.person, role: lead.role, intent: lead.intent,
              property: lead.property, sector: lead.sector, valueNum: lead.valueNum, value: lead.value,
              phone: lead.phone, email: lead.email, website: lead.website, address: lead.address, notes: lead.notes })
          }
          existingUrls.add(url)
          process.stdout.write(`  W${workerId} → ${extracted.length} leads (total: ${allLeads.length})\n`)
        }

        if (processed % 10 === 0 && !mutex.saving) {
          mutex.saving = true
          saveProgress(allLeads, dataDir)
          mutex.saving = false
        }
      }
      await page.close()
    }

    await Promise.all(Array.from({ length: WORKERS }, (_, i) => worker(i + 1)))

  } finally {
    await browser.close()
  }

  saveProgress(allLeads, dataDir)
  console.log(`\n✓ Complete! ${allLeads.length} total leads in data/leads.json`)
}

main().catch(console.error)
